<?php
namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
    /**
     * 基类初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 获取网站信息
        $site_info = \app\common\controller\Site::info();
        $this->assign('site',$site_info['data']);
        // 检查用户session是否存在
        $session_username = session('username');
        if(empty($session_username)) {
            $result = array('code'=>1,'message'=>'user is not login');
            echo json_encode($result);
            $this->redirect('/index/login/index');
            exit;
        }
        // 检查用户是否登录
        $user_info = \app\common\model\User::get(['username'=>$session_username]);
        if(empty($user_info)) {
            $result = array('code'=>1,'message'=>'username is error.');
            echo json_encode($result);
            exit;
        }
        $this->assign('user',$user_info);
    }

    /**
     * 空操作
     * @return array
     */
    public function _empty()
    {
        $request_url = $this->request->domain() . $this->request->url();
        $result = array('code'=>1, 'message'=>'访问的网址:[ ' . $request_url .' ] 不存在');
        return json($result);
    }
}
